export default {
  // AUTH ACTION TYPES
  SET_USER: 'SET_USER',
  SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
  SET_USER_LOADING: 'SET_USER_LOADING',
  CLEAR_USER: 'CLEAR_USER',
  // ALERT ACTION TYPES
  SET_ALERT: 'SET_ALERT',
  REMOVE_ALERT: 'REMOVE_ALERT',
  // INVERNTORY ACTION TYPES
  SET_PRODUCTS: 'SET_PRODUCTS',
  SET_ORDERS: 'SET_ORDERS',
  SET_COUPONS: 'SET_COUPONS',
  CLEAR_INVENTORY: 'CLEAR_INVENTORY'
}