export default {
  // AUTH ACTION TYPES
  SET_USER: 'SET_USER',
  SET_USER_LOADING: 'SET_USER_LOADING',
  CLEAR_USER: 'CLEAR_USER',
  // ALERT ACTION TYPES
  SET_ALERT: 'SET_ALERT',
  REMOVE_ALERT: 'REMOVE_ALERT'
}