export default {
	// AUTH ACTION TYPES
	SET_USER: 'SET_USER',
	SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
	SET_USER_LOADING: 'SET_USER_LOADING',
	CLEAR_USER: 'CLEAR_USER',
	SET_CHECKOUT_ROLE: 'SET_CHECKOUT_ROLE',
	SET_GUEST: 'SET_GUEST',

	// ALERT ACTION TYPES
	SET_ALERT: 'SET_ALERT',
	REMOVE_ALERT: 'REMOVE_ALERT',
	SET_MODAL_MESSAGE: 'SET_MODAL_MESSAGE',

	// INVERNTORY ACTION TYPES
	SET_INVENTORY_LOADING: 'SET_INVENTORY_LOADING',
	SET_CATEGORY_PRODUCTS: 'SET_CATEGORY_PRODUCTS',
	SET_PRODUCTS: 'SET_PRODUCTS',
	SET_PRODUCT: 'SET_PRODUCT',
	SET_REVIEWS: 'SET_REVIEWS',
	CLEAR_PRODUCTS: 'CLEAR_PRODUCTS',
	SET_CATEGORIES: 'SET_CATEGORIES',
	SET_CATEGORY: 'SET_CATEGORY',
	CLEAR_CATEGORIES: 'CLEAR_CATEGORIES',
	SET_ORDERS: 'SET_ORDERS',
	CLEAR_ORDERS: 'CLEAR_ORDERS',
	SET_COUPONS: 'SET_COUPONS',
	SET_COUPON: 'SET_COUPON',
	CLEAR_COUPONS: 'CLEAR_COUPONS',
	CLEAR_INVENTORY: 'CLEAR_INVENTORY',

	// PROFILE ACTION TYPES
	SET_USER_ORDERS: 'SET_USER_ORDERS',
	SET_USER_ADDRESSES: 'SET_USER_ADDRESSES',
	SET_USER_CARD: 'SET_USER_CARD',
	SET_USER_ADDRESS: 'SET_USER_ADDRESS',
	SET_USER_CARDS: 'SET_USER_CARDS',
	SET_PROFILE_LOADING: 'SET_PROFILE_LOADING',
	CLEAR_PROFILE: 'CLEAR_PROFILE',

	// CART ACTION TYPES
	SET_CART_ID: 'SET_CART_ID',
	SET_CART_PRODUCTS: 'SET_CART_PRODUCTS',
	CLEAR_CART: 'CLEAR_CART',
	SET_STEP_PROGRESS: 'SET_STEP_PROGRESS',
	SET_BILLING_ADDRESS: 'SET_BILLING_ADDRESS',
	SET_SHIPPING_ADDRESS: 'SET_SHIPPING_ADDRESS',

	// PAYMENT ACTION TYPES
	SET_ORDER_ID: 'SET_ORDER_ID',
	SET_PAYPAL_ORDER_ID: 'SET_PAYPAL_ORDER_ID',
	SET_RAZORPAY_ORDER_ID: 'SET_RAZORPAY_ORDER_ID',
	SET_COINBASE_ORDER_ID: 'SET_COINBASE_ORDER_ID',
	CLEAR_ORDER: 'CLEAR_ORDER'
}
